<a href="https://colab.research.google.com/github/PepiMartin28/ETL-Project/blob/main/Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook we transform the data that we extract from the notebook "Extraction"

In [ ]:
import pandas as pd
import numpy as np
import csv

First read the csv to obtain the dataframe

In [ ]:
df = pd.read_csv('put your path here')

In [ ]:
df.head()

,league_id,league_name,season,id,name,matches_played,wins,draws,losses,season_points,goals_scored,shots_on_target,goals_against,shots_against,goal_diff,clean_sheets,yellow_cards,red_cards
0,9,Premier League,2000-2001,0,Manchester Utd,38,24,8,6,80,79,251,31,140,48,17,44.0,3.0
1,9,Premier League,2000-2001,1,Arsenal,38,20,10,8,70,63,267,38,133,25,17,48.0,3.0
2,9,Premier League,2000-2001,2,Liverpool,38,20,9,9,69,71,228,39,165,32,14,53.0,4.0
3,9,Premier League,2000-2001,3,Leeds United,38,20,8,10,68,64,229,43,162,21,11,72.0,3.0
4,9,Premier League,2000-2001,4,Ipswich Town,38,20,6,12,66,57,205,42,157,15,13,32.0,2.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2242 entries, 0 to 2241
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   league_id        2242 non-null   int64
 1   league_name      2242 non-null   object
 2   season           2242 non-null   object
 3   id               2242 non-null   int64
 4   name             2242 non-null   object
 5   matches_played   2242 non-null   int64
 6   wins             2242 non-null   int64
 7   draws            2242 non-null   int64
 8   losses           2242 non-null   int64
 9   season_points    2242 non-null   int64
 10  goals_scored     2242 non-null   int64
 11  shots_on_target  2242 non-null   int64
 12  goals_against    2242 non-null   int64
 13  shots_against    2242 non-null   int64
 14  goal_diff        2242 non-null   int64
 15  clean_sheets     2242 non-null   int64
 16  yellow_cards     2169 non-null   float64
 17  red_cards        2167 non-null   float64
dtypes: float64(2), int64(13), object(3)
memory usage: 315.4+ KB

Then, create four new columns:

* goals_scored/90
* shots_on_target/90
* goals_against/90
* shots_against/90

In [ ]:
df['goals_scored/90'] = np.round((df['goals_scored'] / df['matches_played']), 1)

In [ ]:
df['goals_against/90'] = np.round((df['goals_against'] / df['matches_played']), 1)

In [ ]:
df['shots_on_target/90'] = np.round((df['shots_on_target'] / df['matches_played']), 1)

In [ ]:
df['shots_against/90'] = np.round((df['shots_against'] / df['matches_played']), 1)

After, reorder the columns

In [ ]:
df = df[['league_id', 'league_name', 'season', 'id', 'name', 'matches_played', 'wins', 'draws', 'losses', 'season_points',
         'goals_scored', 'goals_scored/90', 'shots_on_target','shots_on_target/90',
         'goals_against', 'goals_against/90', 'shots_against', 'shots_against/90','goal_diff',
         'clean_sheets','yellow_cards', 'red_cards']]

In [ ]:
df.head()

,league_id,league_name,season,id,name,matches_played,wins,draws,losses,season_points,...,shots_on_target,shots_on_target/90,goals_against,goals_against/90,shots_against,shots_against/90,goal_diff,clean_sheets,yellow_cards,red_cards
0,9,Premier League,2000-2001,0,Manchester Utd,38,24,8,6,80,...,251,6.6,31,0.8,140,3.7,48,17,44.0,3.0
1,9,Premier League,2000-2001,1,Arsenal,38,20,10,8,70,...,267,7.0,38,1.0,133,3.5,25,17,48.0,3.0
2,9,Premier League,2000-2001,2,Liverpool,38,20,9,9,69,...,228,6.0,39,1.0,165,4.3,32,14,53.0,4.0
3,9,Premier League,2000-2001,3,Leeds United,38,20,8,10,68,...,229,6.0,43,1.1,162,4.3,21,11,72.0,3.0
4,9,Premier League,2000-2001,4,Ipswich Town,38,20,6,12,66,...,205,5.4,42,1.1,157,4.1,15,13,32.0,2.0

Change the type of the columns "yeloow_cards" and "red_cards"

In [ ]:
df['yellow_cards'] = np.array(df['yellow_cards'], dtype=int)

In [ ]:
df['red_cards'] = np.array(df['red_cards'], dtype=int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2242 entries, 0 to 2241
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   league_id           2242 non-null   int64
 1   league_name         2242 non-null   object
 2   season              2242 non-null   object
 3   id                  2242 non-null   int64
 4   name                2242 non-null   object
 5   matches_played      2242 non-null   int64
 6   wins                2242 non-null   int64
 7   draws               2242 non-null   int64
 8   losses              2242 non-null   int64
 9   season_points       2242 non-null   int64
 10  goals_scored        2242 non-null   int64
 11  goals_scored/90     2242 non-null   float64
 12  shots_on_target     2242 non-null   int64
 13  shots_on_target/90  2242 non-null   float64
 14  goals_against       2242 non-null   int64
 15  goals_against/90    2242 non-null   float64
 16  shots_against       2242 non-null   int64
 17  shots_against/90    2242 non-null   float64
 18  goal_diff           2242 non-null   int64
 19  clean_sheets        2242 non-null   int64
 20  yellow_cards        2242 non-null   int64
 21  red_cards           2242 non-null   int64
dtypes: float64(4), int64(15), object(3)
memory usage: 385.5+ KB

Finally export the dataframe as a csv file

In [ ]:
df.to_csv('put your path here', index=False)